---
title: Testing
papersize: a4paper
# classoption: twocolumn
classes: report
titlepage: true
# background-image: skyline.jpg
# titlepage-background: skyline.jpg
header-right:  \includegraphics[scale=0.2]{logo.png}
colorlinks: true
bibliography: references.bib
template: template.tex
glossary: true
include-after:
    - \printglossary
    - \printglossaries
    - \printindex
---